name: SuperLinter

on: [push, pull_request]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_ALL_CODEBASE: false
          LOG_LEVEL: DEBUG

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/reviewcollector/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd backend
          pytest tests/test_reviewcollector.py


  deploy-product-comparator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy Product Comparator Service
        run: |
          cd backend/productcomparator
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/sentimentor-productcomparator.git
          git add .
          git commit -m "Deploy product comparator from CI"
          git push heroku master --force

  deploy-sentiment-analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy Sentiment Analyzer Service
        run: |
          cd backend/sentimentanalyzer
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/sentimentor-sentimentanalyzer.git
          git add .
          git commit -m "Deploy sentiment analyzer from CI"
          git push heroku master --force

  deploy-review-collector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy Review Collector Service
        run: |
          cd backend/reviewcollector
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/sentimentor-reviewcollector.git
          git add .
          git commit -m "Deploy review collector from CI"
          git push heroku master --force

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy Frontend to Heroku
        run: |
          cd frontend
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/sentimentor-frontend.git
          git add .
          git commit -m "Deploy frontend from CI"
          git push heroku master --force
